"use client";

import { motion } from "framer-motion";
import { Container } from "@/components/shared/container";
import { Zap, Globe, Palette, BarChart3, Shield, Layers } from "lucide-react";

const teasers = [
  {
    icon: Zap,
    title: "Lightning-fast builds",
    description: "Describe your idea and watch it come to life in seconds, not days.",
  },
  {
    icon: Globe,
    title: "Global edge deployment",
    description: "Your store ships to the nearest edge node automatically. Zero config.",
  },
  {
    icon: Palette,
    title: "AI-driven design",
    description: "On-brand storefronts that feel handcrafted — generated by AI.",
  },
  {
    icon: BarChart3,
    title: "Built-in analytics",
    description: "Revenue, traffic, and conversion insights without third-party scripts.",
  },
  {
    icon: Shield,
    title: "Enterprise-grade security",
    description: "SSL, DDoS protection, and SOC-2 compliance out of the box.",
  },
  {
    icon: Layers,
    title: "Extensible by design",
    description: "Plugins, webhooks, and a headless API for when you need more.",
  },
];

const cardVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { duration: 0.45, ease: "easeOut" as const, delay: i * 0.07 },
  }),
};

export function WaitlistFeatures() {
  return (
    <section className="relative overflow-hidden border-t border-border py-24 sm:py-28">
      <div className="bg-grid pointer-events-none absolute inset-0 opacity-40" />
      <div className="pointer-events-none absolute top-0 left-1/2 h-[26rem] w-[40rem] -translate-x-1/2 -translate-y-1/2 rounded-full bg-success/[0.06] blur-3xl" />

      <Container className="relative">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-60px" }}
          transition={{ duration: 0.5, ease: "easeOut" }}
          className="mx-auto max-w-xl text-center"
        >
          <span className="text-xs font-medium uppercase tracking-wider text-success">
            What&apos;s coming
          </span>
          <h2 className="mt-3 text-2xl leading-[1.15] font-medium text-balance sm:text-3xl">
            Everything you need. Nothing you don&apos;t.
          </h2>
          <p className="mt-4 text-sm text-muted-foreground text-balance">
            We&apos;re building the next generation of commerce infrastructure. Here&apos;s a
            sneak peek at what&apos;s on the way.
          </p>
        </motion.div>

        <div className="mt-14 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {teasers.map((item, i) => (
            <motion.div
              key={item.title}
              custom={i}
              variants={cardVariants}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: "-40px" }}
              className="group rounded-2xl border border-border bg-card p-6 transition-colors hover:border-border hover:bg-card/80"
            >
              <div className="mb-4 flex size-10 items-center justify-center rounded-xl border border-border bg-background">
                <item.icon className="size-5 text-success" strokeWidth={1.5} />
              </div>
              <h3 className="text-sm font-medium">{item.title}</h3>
              <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">
                {item.description}
              </p>
            </motion.div>
          ))}
        </div>
      </Container>
    </section>
  );
}
